// Generated by CoffeeScript 1.6.3
(function() {
  var Log,
    __slice = [].slice;

  Log = {
    trace: true,
    logPrefix: '[app]:',
    log: function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (!this.trace) {
        return;
      }
      if (this.logPrefix) {
        args.unshift(this.logPrefix);
      }
      if (typeof console !== "undefined" && console !== null) {
        if (typeof console.log === "function") {
          console.log.apply(console, args);
        }
      }
      return this;
    }
  };

  _.extend(Backbone.Collection.prototype, Log);

  _.extend(Backbone.Model.prototype, Log);

  _.extend(Backbone.View.prototype, Log);

  _.extend(Backbone.Router.prototype, Log);

  Backbone.Log = Log;

}).call(this);
